### ISSUE TITLE
Test `dev`-branch doesn't break existing hrl3 experiments

### ISSUE THREAD

**Issue by JorisVincent** [computational-psychology/hrl#7]

**Comment by guillermoaguilar** [comment]
Things to test 
- [X] Installation  in environment

Template experiments
older mlcm and matching template experiments run in...
- [X] laptop
- [ ] Siemens
- [ ] ViewPixx

new  template experiments (show_stimuli, adjustment) runs
- [X] laptop
- [ ] Siemens
- [ ] Viewpixx

- [ ] Calibration / linerarization works
- [ ] Checking monitor rate works
- [X] hrl-util tests standard
- [X] hrl-util tests class
- [ ] hrl-util datapixx

HRL3 experiments work
- [ ] white scaling project: scaling and matching
- [ ] Lisa's SBC scaling
- [ ] Jarls' contour app / with mouse / with wacom pad
- [ ] Lynn's edge experiment
